export const unit1Vocabulary = [
  {en:'media',de:'Medien',cat:'Media'},
  {en:'screen',de:'Bildschirm',cat:'Media'},
  {en:'download',de:'herunterladen',cat:'Media'},
  {en:'phone',de:'anrufen, telefonieren',cat:'Media'},
  {en:'camera',de:'Fotoapparat, Kamera',cat:'Media'},
  {en:'games console',de:'Spielkonsole',cat:'Media'},
  {en:'on TV',de:'im Fernsehen',cat:'Media'},
  {en:'be on',de:'gezeigt werden; stattfinden',cat:'Media'},
  {en:'news',de:'Nachrichten',cat:'Media'},
  {en:'international',de:'international',cat:'Media'},
  {en:'gamer',de:'Spieler, Gamer',cat:'Media'},
  {en:'exciting',de:'aufregend',cat:'Media'},
  {en:'test',de:'testen',cat:'Media'},
  {en:'company',de:'Firma, Gesellschaft',cat:'Media'},
  {en:'calendar',de:'Kalender',cat:'Media'},
  {en:'stadium',de:'Stadion',cat:'Media'},
  {en:'match',de:'Spiel, Wettkampf',cat:'Media'},
  {en:'winner',de:'Gewinner/in, Sieger/in',cat:'Media'},
  {en:'subject',de:'Thema',cat:'Media'},
  {en:'problem',de:'Problem',cat:'Media'},
  {en:'prize',de:'Preis, Gewinn',cat:'Media'},
  {en:'another',de:'ein/e andere/r/s; noch ein/e',cat:'Media'},
  {en:'go wrong',de:'schiefgehen',cat:'Media'},
  {en:'programme',de:'(Fernseh-)Sendung',cat:'Media'},
  {en:'detective',de:'Detektiv/in',cat:'Media'},
  {en:'detective series',de:'Krimiserie',cat:'Media'},
  {en:'documentary',de:'Dokumentarfilm',cat:'Media'},
  {en:'reality',de:'Realität, Wirklichkeit',cat:'Media'},
  {en:'soap opera',de:'Seifenoper, Soap',cat:'Media'},
  {en:'crime',de:'Verbrechen, Kriminalität',cat:'Media'},
  {en:'real',de:'echt, wirklich',cat:'Media'},
  {en:'type (of)',de:'Art, Sorte',cat:'Media'},
  {en:'survey',de:'Umfrage',cat:'School'},
  {en:'count',de:'zählen',cat:'School'},
  {en:'chat (with)',de:'sich unterhalten (mit)',cat:'School'},
  {en:'safe',de:'sicher, gefahrlos',cat:'School'},
  {en:'more than',de:'mehr als',cat:'School'},
  {en:'dark',de:'dunkel',cat:'People'},
  {en:'straight',de:'gerade; glatt (Haare)',cat:'People'},
  {en:'curly',de:'lockig',cat:'People'},
  {en:'bald',de:'kahl, glatzköpfig',cat:'People'},
  {en:'braces',de:'Zahnklammer',cat:'People'},
  {en:'tooth',de:'Zahn',cat:'People'},
  {en:'glasses',de:'Brille',cat:'People'},
  {en:'young',de:'jung',cat:'People'},
  {en:'kind',de:'nett, freundlich',cat:'People'},
  {en:'serious',de:'ernst',cat:'People'},
  {en:'shy',de:'scheu, schüchtern',cat:'People'},
  {en:'e-friend',de:'E-Mail-Freund/in',cat:'People'},
  {en:'eye',de:'Auge',cat:'People'},
  {en:'stand',de:'stehen, sich hinstellen',cat:'School'},
  {en:'jacket',de:'Jacke',cat:'School'},
  {en:'exercise',de:'Übung, Aufgabe',cat:'School'},
  {en:'cook',de:'Koch, Köchin',cat:'School'},
  {en:'repeat',de:'wiederholen',cat:'School'},
  {en:'message in a bottle',de:'Flaschenpost',cat:'Story'},
  {en:'by the sea',de:'am Meer',cat:'Story'},
  {en:'situation',de:'Situation',cat:'Story'},
  {en:'path',de:'Weg, Pfad',cat:'Story'},
  {en:'suddenly',de:'plötzlich, auf einmal',cat:'Story'},
  {en:'seem',de:'erscheinen, scheinen',cat:'Story'},
  {en:'joke',de:'Witz, Scherz',cat:'Story'},
  {en:'alone',de:'allein',cat:'Story'},
  {en:'piece of paper',de:'Stück Papier, Zettel',cat:'Story'},
  {en:'through',de:'durch',cat:'Story'},
  {en:'writing',de:'Schrift',cat:'Story'},
  {en:'trust',de:'vertrauen',cat:'Story'},
  {en:'if',de:'wenn, falls',cat:'Story'},
  {en:'writer',de:'Autor/in, Verfasser/in',cat:'Story'},
  {en:'danger',de:'Gefahr',cat:'Story'},
  {en:'head',de:'Kopf',cat:'Story'},
  {en:'maybe',de:'vielleicht',cat:'Story'},
  {en:'experiment',de:'Experiment',cat:'Story'},
  {en:'sand',de:'Sand',cat:'Story'},
  {en:'prove',de:'nachweisen, beweisen',cat:'Story'},
  {en:'wood',de:'Holz, Wald',cat:'Story'},
  {en:'drop',de:'(sich) fallen lassen',cat:'Story'},
  {en:'rock',de:'Felsen',cat:'Story'},
  {en:'presentation',de:'Referat, Präsentation',cat:'School'}
];

export const unit1Phrases = [
  {en:'put ... away',de:'... weglegen, zur Seite legen'},
  {en:'put up your hand',de:'sich melden, aufzeigen'},
  {en:'Repeat after me.',de:'Sprich / Sprecht mir nach.'},
  {en:"What's for homework?",de:'Was haben wir als Hausaufgabe(n) auf?'},
  {en:'pick sth up',de:'etwas aufheben, etwas hochheben'},
  {en:'go around and around',de:'sich immer wieder drehen'},
  {en:'onto the rocks',de:'auf die Felsen (hinauf)'},
  {en:'more than',de:'mehr als'},
  {en:'go wrong',de:'schiefgehen'},
  {en:'by the sea',de:'am Meer'}
];
