import {enableTapDrag} from './dragdrop.js';
const norm=(s,ignore)=>{s=(s??'').trim().toLowerCase();if(ignore){s=s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9äöüß ]/gi,'').replace(/(.)\1{1,}/g,'$1')}return s};
const el=(id,root=document)=>root.querySelector('#'+id);
function ids(cfg){return {exercise:cfg.ids?.exercise||'exercise',score:cfg.ids?.score||'score',total:cfg.ids?.total||'total',check:cfg.ids?.checkBtn||'checkBtn',fresh:cfg.ids?.newBtn||'newBtn',result:cfg.ids?.result||'result'}}
function finish(cfg,score,total,details=[]){const I=ids(cfg);el(I.score).textContent=score;el(I.total).textContent=total;const r=el(I.result);r.textContent=score===total?'Alles richtig! 🎉':`${score} von ${total} richtig.`;r.className='result '+(score===total?'good':'bad');r.dataset.details=JSON.stringify(details);document.dispatchEvent(new CustomEvent('exercise:scored',{detail:{score,total,details}}));}
export function mountChoice(cfg){const I=ids(cfg),host=el(I.exercise);host.innerHTML=cfg.questions.map((q,i)=>`<div class="item"><strong>${i+1}. ${q.q}</strong>${q.options.map(o=>`<label class="option"><input type="radio" name="q${i}" value="${o}"> ${o}</label>`).join('')}</div>`).join('');el(I.check).onclick=()=>{let s=0,d=[];cfg.questions.forEach((q,i)=>{const v=host.querySelector(`input[name=q${i}]:checked`)?.value||'';if(v===q.answer)s++;else d.push({q:q.q,given:v,answer:q.answer})});finish(cfg,s,cfg.questions.length,d)};el(I.fresh).onclick=()=>mountChoice(cfg)}
export function mountCloze(cfg){const I=ids(cfg),host=el(I.exercise);host.innerHTML=cfg.items.map((x,i)=>`<div class="item">${x.before}<input data-i="${i}" type="text" aria-label="Lücke ${i+1}">${x.after||''}</div>`).join('');el(I.check).onclick=()=>{let s=0,d=[];cfg.items.forEach((x,i)=>{const v=host.querySelector(`[data-i="${i}"]`).value;if(norm(v,cfg.ignoreSpelling)===norm(x.answer,cfg.ignoreSpelling))s++;else d.push({given:v,answer:x.answer})});finish(cfg,s,cfg.items.length,d)};el(I.fresh).onclick=()=>mountCloze(cfg)}
export function mountType(cfg){const I=ids(cfg),host=el(I.exercise);host.innerHTML=cfg.items.map((x,i)=>`<div class="row item"><span style="min-width:180px">${x.prompt}</span><input data-i="${i}" type="text"></div>`).join('');el(I.check).onclick=()=>{let s=0,d=[];cfg.items.forEach((x,i)=>{const v=host.querySelector(`[data-i="${i}"]`).value;if(norm(v,cfg.ignoreSpelling)===norm(x.answer,cfg.ignoreSpelling))s++;else d.push({prompt:x.prompt,given:v,answer:x.answer})});finish(cfg,s,cfg.items.length,d)};el(I.fresh).onclick=()=>mountType(cfg)}
export function mountMark(cfg){const I=ids(cfg),host=el(I.exercise);const words=cfg.text.split(/(\s+)/);host.innerHTML=`<div class="item">${words.map((w,i)=>/\s+/.test(w)?w:`<span class="mark-word" tabindex="0" data-i="${i}">${w}</span>`).join('')}</div>`;host.querySelectorAll('.mark-word').forEach(w=>{const f=()=>w.classList.toggle('marked');w.onclick=f;w.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')f()}});el(I.check).onclick=()=>{const chosen=[...host.querySelectorAll('.marked')].map(x=>x.textContent.replace(/[.,!?]/g,''));const targets=cfg.answers;let s=chosen.filter(x=>targets.includes(x)).length-(chosen.filter(x=>!targets.includes(x)).length);s=Math.max(0,s);finish(cfg,s,targets.length,{chosen,targets})};el(I.fresh).onclick=()=>mountMark(cfg)}
export function mountOrder(cfg){const I=ids(cfg),host=el(I.exercise);let order=[...cfg.parts].sort(()=>Math.random()-.5);host.innerHTML=`<div class="order-list" id="pool">${order.map((p,i)=>`<button class="chip" data-val="${p}">${p}</button>`).join('')}</div><div class="dropzone order-slot" data-dropzone id="orderTarget"></div>`;const target=host.querySelector('#orderTarget');host.querySelectorAll('.chip').forEach(b=>b.onclick=()=>target.appendChild(b));target.onclick=e=>{if(e.target.classList.contains('chip'))host.querySelector('#pool').appendChild(e.target)};el(I.check).onclick=()=>{const got=[...target.querySelectorAll('.chip')].map(x=>x.dataset.val);const ok=JSON.stringify(got)===JSON.stringify(cfg.answer);finish(cfg,ok?1:0,1,{got,answer:cfg.answer})};el(I.fresh).onclick=()=>mountOrder(cfg)}
export function mountSort(cfg){const I=ids(cfg),host=el(I.exercise);host.innerHTML=`<div id="cards">${cfg.items.map((x,i)=>`<button class="chip" data-val="${x.text}" data-cat="${x.category}">${x.text}</button>`).join('')}</div><div class="two">${cfg.categories.map(c=>`<div><strong>${c}</strong><div class="dropzone" data-dropzone data-cat="${c}"></div></div>`).join('')}</div>`;const items=[...host.querySelectorAll('.chip')],zones=[...host.querySelectorAll('[data-dropzone]')];enableTapDrag({items,zones,onDrop:(item,zone)=>zone.appendChild(item)});el(I.check).onclick=()=>{let s=0,d=[];items.forEach(x=>{const got=x.parentElement.dataset.cat;if(got===x.dataset.cat)s++;else d.push({item:x.dataset.val,given:got,answer:x.dataset.cat})});finish(cfg,s,items.length,d)};el(I.fresh).onclick=()=>mountSort(cfg)}
export function mountMatch(cfg){const I=ids(cfg),host=el(I.exercise);host.innerHTML=`<div id="cards">${cfg.pairs.map((x,i)=>`<button class="chip" data-val="${x.left}" data-key="${i}">${x.left}</button>`).join('')}</div><div class="stack">${cfg.pairs.map((x,i)=>`<div class="dropzone" data-dropzone data-key="${i}"><strong>${x.right}</strong></div>`).join('')}</div>`;const items=[...host.querySelectorAll('.chip')],zones=[...host.querySelectorAll('[data-dropzone]')];enableTapDrag({items,zones,onDrop:(item,zone)=>zone.appendChild(item)});el(I.check).onclick=()=>{let s=0,d=[];items.forEach(x=>{const got=x.parentElement.dataset.key;if(got===x.dataset.key)s++;else d.push({item:x.dataset.val})});finish(cfg,s,items.length,d)};el(I.fresh).onclick=()=>mountMatch(cfg)}
